### ISSUE TITLE
fix: change NextNProgress bar in dark and light mode

### ISSUE THREAD

**Issue by kr-anurag** [avneesh0612/hashnode-stats#40]
### Description

Well, the progress bar isn't fully visible in light mode, so it's better to change it according to modes

**Comment by jesusj0o** [comment]
Hello there! I would like to give this issue a try :) 
Do i have to ask for some user credentials to sign in?

**Comment by avneesh0612** [comment]
Nope, no env needed. Go ahead!

**Comment by suhaasya** [comment]
is anyone working on this issue?? if anyone isn't you can assign me.
I had already fixed it too. I just need to take some feedback from you.

**Comment by avneesh0612** [comment]
I will assign it to you!
